apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: laracamp-stg
data:
  MYSQL_DATABASE: laracamp_db
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laracamp-stg
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: laracamp_user
  MYSQL_PASSWORD: laracamp_pw