apiVersion: v1
kind: Service
metadata:
  name: laracamp
  namespace: laracamp-stg
spec:
  selector:
    app: laracamp-stg
  ports:
    - port: 8000
      name: http
      protocol: TCP
      targetPort: 80
  type: NodePort